### ISSUE TITLE
JEI crash

### ISSUE THREAD

**Issue by Apocrophon** [xJon/The-1.7.10-Pack#1981] opened 2022-09-05 08:14 UTC
I clicked on the Recipes for Dungeon Loot and it crashed my client.
first crashlog: 
[crash-2022-09-05_00.46.29-client.txt](https://github.com/xJon/The-1.7.10-Pack/files/9487890/crash-2022-09-05_00.46.29-client.txt)

Did it again to verify the crash 
![image](https://user-images.githubusercontent.com/24848664/188401447-06a35613-5dd7-4c75-b6b3-45ed1b0462bd.png)
[crash-2022-09-05_01.13.47-client.txt](https://github.com/xJon/The-1.7.10-Pack/files/9487956/crash-2022-09-05_01.13.47-client.txt)
https://mclo.gs/ug4YImL

**Comment by xJon** [comment] 2022-09-05 11:56
Seems to be caused by `neresources.nei.NEIDungeonHandler$CachedDungeonChest.getResult`. I'll see whether someone can help with that

**Comment by quentin452** [comment] 2022-09-05 13:21
Its an issue with enchanting plus

**Comment by Apocrophon** [comment] 2022-09-05 18:23
> 

will test

**Comment by Apocrophon** [comment] 2022-09-05 18:27
not sure where to get a more recent version of NEI 
if you know where it is please link it

**Comment by xJon** [comment] 2022-09-05 18:43
@Apocrophon according to @quentin452 that doesn't help - it seems to be an incompatibility between Enchanting Plus and NotEnoughResources.

**Comment by xJon** [comment] 2022-09-16 00:10
Reported over https://github.com/GTNewHorizons/NotEnoughItems/issues/295. For now I'll close this.

**Comment by xJon** [comment] 2022-10-18 22:57
This is fixed in `0.10.8` :)

**Closed by xJon** 2022-10-18 22:57 UTC
Labels: fixed
