### ISSUE TITLE
When i Tab out my Game Crashes

### ISSUE THREAD

**Issue by RiiVu** [xJon/The-1.7.10-Pack#1644] opened 2019-01-10 19:21 UTC
Hello, my friend has the problem that when he tab out (fullscreen or minimized) his game is crashing he have given minecraft enough ram. i paste the crash report n haste bin here is the link he would apreciate every help and sorry for my bad english :)
https://hastebin.com/qepopafavu.rb

**Comment by xJon** [comment] 2019-01-11 05:39
Does this happen every time you try to tab out of the client?

**Comment by RiiVU** [comment] 2019-01-14 16:14
He says if he trys to tab out his game crash not everytime but very often.

**Comment by xJon** [comment] 2019-07-04 05:21
Hi,
As I couldn't reproduce the bug, I will close the issue.
You can try to update your computer's drivers, it might help and it's always good.
I will reopen the issue if we can find out what causes the issue, or if the crash log can be re-uploaded as I cannot access it anymore.

**Closed by xJon** 2019-07-04 05:21 UTC
Labels: can't reproduce
