### ISSUE TITLE
Can't change Morph keybinds

### ISSUE THREAD

**Issue by mouro001** [xJon/The-1.7.10-Pack#1774] opened 2019-06-22 19:14 UTC
Am I blind or is there no option to change the controls for the Morph mod?
Spent a lot of time looking how to change the keybind and I don't see it.
Do I have to change it through the config files?

**Comment by xJon** [comment] 2019-06-23 08:02
In settings, you need to press the "O" key to get to the settings of the iChun mods. I'm pretty sure that should work, but also you can manually go to the mod's config file and edit it.

**Comment by mouro001** [comment] 2019-06-23 10:15
Tried pressing "O" in the Options Menu and it opens the controls page and automatically types "O" in the search bar.
Tried pressing on the controls page and it does nothing

**Comment by mouro001** [comment] 2019-06-23 10:29
Could it be because of the Custom Menu?
![2019-06-23_11-28-15](https://user-images.githubusercontent.com/8522686/59974941-09a07380-95aa-11e9-8dd5-728a01d46298.gif)

**Comment by xJon** [comment] 2019-06-23 12:24
Oh, I might've remembered it wrong, try to press 0.

**Comment by mouro001** [comment] 2019-06-23 12:33
Nope, 0 doesn't do anything at all

**Comment by mouro001** [comment] 2019-06-23 12:37
Aparently you are supposed to be able to click on "Hit O to view more options" but that doesn't seem to be working. 
Is there any mod that changes the menus on this modpack? I could try remove that mod and check if it works

**Comment by xJon** [comment] 2019-06-24 02:06
Can you try to remove the Controlling mod?

**Comment by mouro001** [comment] 2019-06-24 21:33
That fixed the issue. Thank you very much

**Comment by xJon** [comment] 2019-06-25 08:23
You're welcome. Will try to look into this minor issue for the next version of the pack.

**Comment by xJon** [comment] 2019-07-04 05:29
I see that this is actually a duplicate of https://github.com/xJon/The-1.7.10-Pack/issues/1714.
Will close this one.

**Closed by xJon** 2019-07-04 05:29 UTC
Labels: duplicate, investigation required
