### ISSUE TITLE
Thermal Expansion machines resetting (A few issues regarding 10.7)

### ISSUE THREAD

**Issue by phantomnerifes** [xJon/The-1.7.10-Pack#1984] opened 2022-09-26 09:34 UTC
been playing on a modded server for this modpack for a while now, but since it's updated to 10.7 there's been quite a few resounding issues that me and some friends keep encountering on both multiplayer and singleplayer:

**Thermal Expansion**: machines (pulverizers, redstone furnaces, induction smelters, etc.) will reset to basic tier and have all augments and items stored within deleted and default their rotation to face north (this will happen anytime you either disconnect from the server or let the chunk unload, can't confirm which one; removing and replacing said machines doesn't fix the issue), as well as tesseracts refusing to transfer items, liquids, and energy (removing and replacing tesseracts seems to fix the issue until the chunk unloads or you log out)
**AE2**: crystal chargers and ME chests will sometimes go invisible but still somewhat functional until you break them and put them back down, and ME controllers will change to a deactivated texture despite receiving energy.
**Ender IO**: Conduits will sometimes disconnect from whichever system they're connected to and refuse to transfer items, liquids, and energy, and dimensional transceivers will refuse to send items, liquids, and energy across networks (both conduits and transceivers require removal and replacement for them to function again until you either log off or unload the chunk which restarts the problem)
**Vanilla Minecraft**: entering the GUI of a beacon will crash the server/game and send you back to the main screen
(i am unsure if there is any confirmable issues with mekanism but my friend was making a lot of complaints about his energy not being used efficiently, again i can't confirm because i wasn't there nor do i really know much about mekanism, just wanted to make it aware)
**Big Reactors/Advanced solar panels?**: yellowrium dust that is cooked in any smelter becomes uranium from advanced solar panels (i'm unsure if this is an item ID thing or recipe IDs, just slightly annoying to grind dust then make it into something that can't be made into blocks lol)
**Railcraft**: Void chests refuse to delete items placed in them until the chest is removed and put back down

So far all of these issues (aside from the mekanism and Big reactor ones due to insufficient evidence) were not issues in 10.6 but started up as such in 10.7 so i'm unsure what was changed/added for those. it's honestly been very annoying to have to manually reset most of the items placed for them to function normally, so any possible input or fixes would be appreciated

**Comment by xJon** [comment] 2022-09-26 12:52
Hey, thanks for the report!
Beyond the Beacon GUI crash (which is fixed in the latest version of ArchaicFix), and the Yellowrium thing (which is caused by the addition of UniDict & Advanced Solar Panels and will be changed in the next update), the other issues don't seem reproducible. This will probably require further troubleshooting on your end - are you playing on a server with plugins? Can you reproduce it outside that server?

**Comment by phantomnerifes** [comment] 2022-09-28 01:15
there's no custom plugins being used on the base pack but we're running our server off of ServerMiner so that could be one of the reasons it was happening.

as for replicating the bugs i mentioned earlier in singleplayer, for some reason i could replicate the issues yesterday in both multiplayer and singleplayer, but today i am unable to replicate them aside from the AE2 ME Controller appearing deactivated in multiplayer despite being fully powered. i will have to get a hold of the server owner and see if they updated something while I was away and get back to this with an update.
![ME Control](https://user-images.githubusercontent.com/114394657/192665163-3c699f5e-27bc-4a6a-a61e-a25994855ee9.png)

**Comment by phantomnerifes** [comment] 2022-09-28 01:16
there's no custom plugins being used on the base pack but we're running our server off of ServerMiner so that could be one of the reasons it was happening.

as for replicating the bugs i mentioned earlier in singleplayer, for some reason i could replicate the issues yesterday in both multiplayer and singleplayer, but today i am unable to replicate them aside from the AE2 ME Controller appearing deactivated in multiplayer despite being fully powered. i will have to get a hold of the server owner and see if they updated something while I was away and get back to this with an update.

edit: (accidentally closed the thread because i'm an idiot and pressed the wrong button)
![ME Control](https://user-images.githubusercontent.com/114394657/192665328-dd84b4a2-06cf-4f74-bf41-363ad2b0e9e3.png)

**Comment by xJon** [comment] 2022-09-28 03:23
If you can reproduce this issue, try troubleshooting it - please make sure your server is running the latest normal Forge version, and try testing without CoreTweaks and ArchaicFix, as they are the mods that affect a lot of stuff from the last update.
If those don't change anything, please also test without FalsePatternLib (& AnimFix on client), MixingASM, ASMFixes, backport5160, & BugTorch.

I will say, these newly added mods were properly tested in a lot of other environments so I doubt they are the cause. I asked some other people over the modpack's Discord whether they encouraged these issues and it doesn't seem so, so it's quite odd. You didn't modify the modpack in any way? If you reproduced it on singleplayer at some point, maybe it's a rare issue that appears only sometimes? I'm not sure, but I was unable to reproduce it myself.

**Comment by phantomnerifes** [comment] 2022-10-01 21:42
i went and asked my friend who owns the server if he did anything but he wasn't sure what was wrong either, as well as other players that were online, all of them said they haven't noticed anything weird happening either. the only things that i could think of that would cause this strange behavior is switching between 10.6 and 10.7 a few times due to lack of communication between my friends when the server was still in the process of updating to 10.7.

it's already been a few days and so far only the beacon bug is still persisting, everything else i listed off seems to have gone back to normal to my knowledge. i think it was just instability on my own client for everything else though, so it's probably a good idea to wrap things up now.

**Comment by xJon** [comment] 2024-01-04 02:42
The Thermal Expansion machines resetting issue has been identified thanks to @Midnight145 to be caused by ArchaicFix's `fixTEUnloadLag` patch. This will be resolved in the next modpack update, for now that config can be disabled.

**Comment by xJon** [comment] 2024-03-20 01:57
Should be resolved in `0.10.12` :)

**Closed by xJon** 2024-03-20 01:57 UTC
Labels: fixed
