### ISSUE TITLE
Tinkers construct traveller's gloves not giving haste

### ISSUE THREAD

**Issue by Kenny21kc** [xJon/The-1.7.10-Pack#2006] opened 2023-11-25 16:47 UTC
I made traveller's gloves, put 500 redstone on it and it doesn't give me any mining speed buff, it works fine on other modpacks or if I isolate the mod itself, any solutions?

**Comment by xJon** [comment] 2023-11-25 18:55
> it works fine on other modpacks or if I isolate the mod itself, any solutions?

I assume then that it's a mod incomparitibility. I'm currently unable to identify the cause, so I'm not sure how fixable it is.
If you are able to remove mods in order to find the cause, it could prove useful.

**Comment by Kenny21kc** [comment] 2023-11-26 17:43
It's really time consuming, might take a while I don't have much free time.

**Comment by xJon** [comment] 2023-11-26 20:54
I understand, I'll close it for now. Thanks for reporting nevertheless :)

**Closed by xJon** 2023-11-26 20:54 UTC
Labels: wontfix, minor bug
