### ISSUE TITLE
Want to create a server for me and a few friends

### ISSUE THREAD

**Issue by Ninja77677** [xJon/The-1.7.10-Pack#1215] opened 2016-08-31 20:26 UTC
I have everything else done, but im not sure which client only mods and their respective configs to delete. any help would be nice. and yes. i know the mopdack has an official server, but I want to make one just for me and a few friends. any help is greatly appreciated!

**Comment by mandm635** [comment] 2016-08-31 22:56
There is a server download that has all the mods/resources in it. I would recommend using that over a manual install for a pack of this size. The download is located on the Technic site. Keep in mind that the server will probably be very laggy on anything other than a high end pc. I would not attempt without a substantial amount of ram either. Good luck!

**Comment by Ninja77677** [comment] 2016-09-03 16:33
thanks for your help! the server is up and we are happily playing on it!
Also I do have a very high-end PC. so it will work fine. thanks for the
help!

**Comment by mandm635** [comment] 2016-09-03 16:53
Glad to hear it! Have fun!

PS: Could you close this thread if the issue is solved?

**Closed** 2016-09-03 17:04 UTC
Labels: question
