### ISSUE TITLE
Pack server crashing

### ISSUE THREAD

**Issue by kdonley** [xJon/The-1.7.10-Pack#1458] opened 2017-10-08 20:40 UTC
Server worked fine for a week and now its getting this error:

**EDITED BY JON: Please use a paste tool - https://pastebin.com/y0tRZwsa**

**Comment by Azamorn666** [comment] 2017-10-11 10:04
According to this:
https://stackoverflow.com/questions/20777884/com-google-gson-jsonprimitive-cannot-be-cast-to-com-google-gson-jsonobject-error
It seems that there is an issue in the Pneumaticcraft config json files, I'd check that out, try copy pasting them in a json validator to see where the issue is.

**Comment by gogobebe2** [comment] 2018-02-01 00:39
@Azamorn666 Did you ever end up resolving this issue?

**Comment by kdonley** [comment] 2018-02-03 21:30
No, I just have to restore a backup whenever it happens which is about once
a week

**Comment by xJon** [comment] 2018-02-22 17:44
Try to reset PneumaticCraft's config files.

**Comment by xJon** [comment] 2018-04-04 15:45
Closed due to inactivity.
Will reopen if requested.

**Closed by xJon** 2018-04-04 15:45 UTC
Labels: help wanted
